# Generated by Django 5.2.6 on 2025-10-01 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('idhistoria', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fechaapertura', models.DateField()),
                ('observacionesgenerales', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idpaciente', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=150)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('fechanacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('antecedentes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('idadjunto', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('rutaarchivo', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('idodontograma', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fechacreacion', models.DateField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.historiaclinica')),
            ],
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
        migrations.CreateModel(
            name='PiezaDental',
            fields=[
                ('idpieza', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('codigofdi', models.CharField(max_length=2)),
                ('estado', models.CharField(choices=[('Sana', 'Sana'), ('Caries', 'Caries'), ('Tratada', 'Tratada'), ('En tratamiento', 'En tratamiento'), ('Extraída', 'Extraída')], max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('odontograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.odontograma')),
            ],
        ),
    ]
