# Generated by Django 5.2.6 on 2025-10-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_groups_remove_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='idrol',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idusuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
