# Generated by Django 5.2.6 on 2025-10-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idcita', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('horarioini', models.TimeField()),
                ('horafin', models.TimeField()),
                ('estado', models.CharField(choices=[('Agendada', 'Agendada'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada'), ('Confirmada', 'Confirmada'), ('No-Show', 'No-Show')], default='Agendada', max_length=15)),
                ('motivo', models.TextField()),
                ('canalrecordatorio', models.CharField(blank=True, choices=[('SMS', 'SMS'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp')], max_length=20, null=True)),
            ],
        ),
    ]
