# Generated by Django 5.2.6 on 2025-10-01 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_initial'),
        ('usuarios', '0002_remove_usuario_groups_remove_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='odontologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
