# Generated by Django 5.2.6 on 2025-10-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_cita_odontologo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='idcita',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
