# Generated by Django 5.2.6 on 2025-10-01 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atencion', '0001_initial'),
        ('citas', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='cita',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.cita'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.historiaclinica'),
        ),
    ]
